config/routes.rb
Carrie::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {:sessions => "sessions"}

  scope "api" do
    namespace :published do
      resources :los, only: :show
      match '/teams/:team_id/los/:id' => "los#show"
    end

    resources :comments,only: :index do
    end

    resources :answers do
      post 'retroaction', on: :member
      get 'page/:page', :action => :index, :on => :collection
      resources :comments
    end

    match '/home/lo_example' => "home#lo_example"
    resources :retroaction_answers, only: :create
    resources :contacts, only: :create

    resources :teams do
      get 'created', on: :collection
      get 'enrolled', on: :collection
      get 'my_teams', on: :collection
      get 'teams_for_search', on: :collection
      get 'learners', on: :collection
      post 'enroll', on: :member
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :los do
      get 'my_los', on: :collection
      get 'los_for_search', on: :collection
      get 'exercises', on: :collection
      resources :introductions do
        collection {post :sort}
      end
      resources :exercises do
        delete 'delete_last_answers', :on => :member
        resources :questions do
          resources :tips
          resources :test_cases
          collection {post :sort}
        end
        collection { post :sort }
      end
    end
  end

  #get "answers_panel/index"
  #get "answers_panel/answers"

  namespace :newapi do
    resources :users, :only => [:index]
    resources :answers, :only => [:show] do
      member do
        get "connections"
        get "connected_component"
        get "similar"
      end
      collection do
        post "connections", action: :group_connections
        post "group"
      end
    end
    resources :connections, :only => [:create] do
      member do
        delete "reject_connection"
        put "accept_connection"
      end
    end
  end

  namespace :panel do
    #get "retroaction/:answer_id", :action => :retroaction
    #get "index"
    #get "comments"
    #get "explorer"
    resources :teams, only: [:show] do
      resources :los, only: [] do
        get 'overview', on: :member
      end
      resources :users, only: [:show] do
        resources :los, only: [:show] do
          resources :questions, only: [:show] do
            resources :answers, only: [:show] do
              post 'change_correctness', on: :member
              get 'try_again', on: :member
            end
          end
        end
      end
    end
  end

  #namespace :explorer do
  #  get "index"
  #  get "load_users"
  #  post "info_answer"
  #  post "info_connection"
  #  put "search"
  #  put "fulltext_search"
  #end

  namespace :dashboard do
    get "home"

    get "help"
    get "hide_help"

    post "graph_answer_info"
    post "graph_connection_info"

    get "search"
    get "timeline"
    get "graph"
    get "tags"

    put "fulltext_search/page/:page", action: "fulltext_search", as: "fulltext_search"
    put "timeline_search/page/:page", action: "timeline_search", as: "timeline_search"
    put "graph_search/page/:page", action: "graph_search", as: "graph_search"
    put "tags_search/page/:page", action: "tags_search", as: "tags_search"
    put "tags_search_aat", action: "tags_search_aat", as: "tags_search_aat"

    resources :teams, :only => [:new,:edit,:update,:create,:destroy] do
      post :unenroll, on: :member
    end
    namespace :teams do
      get "available"
      post "enroll"
    end

    namespace :answers do
      get "show"
    end

    namespace :connections do
      get "show"
    end

    resources :messages do
      resources :replies, :only => [:create,:destroy]
    end

    namespace :tags do
      get "show"
      put "add_tag"
      post "create_tag"
      delete "remove_tag"
      put "accept_tag"
      put "reject_tag"
    end
  end

  root to: "welcome#index"

  match '*path', to: 'home#index'
end

app/controllers/dashboard/teams_controller.rb
class Dashboard::TeamsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_prof, :only =>[:new, :update, :edit, :create,:destroy]
  before_filter :can_edit?, :only =>[:update, :edit, :destroy]

  layout "dashboard"

  def can_edit?
    unless current_user.id.to_s == Team.find(params[:id]).owner_id.to_s || current_user.admin?
      render_401
    end
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    @team.owner_id = current_user.id
    respond_to do |format|
      if @team.save
        format.html { redirect_to dashboard_teams_available_path, notice: 'Turma criada com sucesso.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to panel_team_path(@team.id), notice: 'Turma atualizada com sucesso.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def enroll
    t = Team.find(params[:team][:id])
    unless t.users.include?(current_user)
      if t.code == params[:password]
        t.users << current_user

        t.save!
      else
        @wrong_code_team_id = t.id
      end
    end
    #@teams = Team.all
    @teams = Team.where(active: true)

    render "available"
  end

  def unenroll
    @team = Team.find(params[:id])

    if @team.users.include?(current_user)
      @team.user_ids = @team.user_ids - [current_user.id]
      @team.save!
    end

    redirect_to dashboard_teams_available_path
  end

  def destroy
    @team = Team.find(params[:id])

    if @team.owner_id == current_user.id
      @team.destroy
    end

    redirect_to dashboard_teams_available_path
  end

  def available
    @teams = Team.where(active: true)
    @teams_unavailable = Team.where(active: false)
  end

end

app/controllers/panel/answers_controller.rb
class Panel::AnswersController < ApplicationController
	layout "dashboard"
	before_filter :authenticate_user!
	before_filter :get_data

	def get_data
		@team = Team.find(params[:team_id])
		@user = User.find(params[:user_id])
		@lo = Lo.find(params[:lo_id])
		@question = Question.find(params[:question_id])
		@answer = Answer.find(params[:id])


		if current_user.prof? && (not current_user.admin?)
			unless current_user.all_team_ids.include?(@answer.team_id)
				render_401
				return false
			end
		end

		unless current_user.prof?
			unless current_user.team_ids.include?(@team.id)
				render_401
				return false
			end
			unless current_user.team_ids.include?(@team.id)
				render_401
				return false
			end
			unless current_user.id == @answer.user_id
				render_401
				return false
			end
		end

	end

	def show
		@comment = Comment.new
		@comment.answer = @answer
		@comment.user_id = current_user.id
		@previous_answers = @answer.previous(5)
		@correct = Answer.where(user_id: params[:user_id], question_id: params[:question_id], correct: true).count > 0 ? true : false
		Log.log_answer_view(current_user.id,@answer.id)
	end

  def change_correctness
    if current_user.admin? || current_user.id == @team.owner_id
      @answer.changed_correctness = true
      options = {:hard_wrap => true, :filter_html => true, :autolink => true,
               :no_intraemphasis => true, :fenced_code => true, :gh_blockcode => true}
      markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
      @answer.changed_correctness_reason = markdown.render(params[:answer][:changed_correctness_reason]).html_safe.gsub(/"/,'&quot').gsub(/\n/,'')
      if @answer.correct
        @answer.correct = false
      else
        @answer.correct = true
      end
      @answer.save!
    end

    redirect_to panel_team_user_lo_question_answer_path(@team,@user,@lo,@question,@answer)
  end

	def try_again
		if @user.id == current_user.id
			if Team.find(@answer.team_id).lo_ids.include?(@answer.lo_id)
				Log.log_answer_try_again_click(current_user.id,@answer.id)
				redirect_to current_user.link_to_question(Question.find(@answer.question_id))
				return
			end
		end

		render_401
	end

end

app/controllers/panel/los_controller.rb
class Panel::LosController < ApplicationController
	layout "dashboard"
	before_filter :authenticate_user!
	before_filter :get_data, :only => [:show]

	def get_data
		@team = Team.find(params[:team_id])
		@user = User.find(params[:user_id])
		@lo = Lo.find(params[:id])

		unless current_user.prof?
			unless current_user.team_ids.include?(@team.id)
				render_401
				return false
			end
			unless current_user.id == @user.id
				render_401
				return false
			end
		end

		if current_user.prof? && (not current_user.admin?)
			unless current_user.all_team_ids.include?(@team.id)
				render_401
				return false
			end
		end
	end

	def show
		@exercises = @lo.exercises

    @team_stats = Hash.new
    @stats = Hash.new
    @exercises.each do |ex|
      @team_stats[ex.id] = Hash.new
      @stats[ex.id] = Hash.new
      ex.questions.each do |q|
        @team_stats[ex.id][q.id] = Statistic.find_or_create_by(:question_id => q.id, :team_id => @team.id)
        @stats[ex.id][q.id] = Statistic.find_or_create_by(:question_id => q.id, :team_id => nil)
      end
    end

    @last_answers = Answer.where(user_id:@user.id,team_id:@team.id,lo_id:@lo.id).desc(:created_at)[0..5]

		Log.log_team_user_lo_view(current_user.id,@team.id,@user.id,@lo.id)

    @recent_activity_data = GraphDataGenerator::team_user_lo_recent_activity(@team.id,@user.id,@lo.id)
	end

  def overview
    @team = Team.find(params[:team_id])
    @lo = Lo.find(params[:id])
    @exercises = @lo.exercises

    if not current_user.admin? and @team.owner_id != current_user.id
      redirect_to panel_index_path
    end

    @team_stats = Hash.new
    @stats = Hash.new
    @exercises.each do |ex|
      @team_stats[ex.id] = Hash.new
      @stats[ex.id] = Hash.new
      ex.questions.each do |q|
        @team_stats[ex.id][q.id] = Statistic.find_or_create_by(:question_id => q.id, :team_id => @team.id)
        @stats[ex.id][q.id] = Statistic.find_or_create_by(:question_id => q.id, :team_id => nil)
      end
    end

		Log.log_team_lo_overview_view(current_user.id,@team.id,@lo.id)
  end
end

app/controllers/panel/questions_controller.rb
class Panel::QuestionsController < ApplicationController
	layout "dashboard"
	before_filter :authenticate_user!
	before_filter :get_data

	def get_data
		@team = Team.find(params[:team_id])
		@user = User.find(params[:user_id])
		@lo = Lo.find(params[:lo_id])
		@question = Question.find(params[:id])

		unless current_user.prof?
			unless current_user.team_ids.include?(@team.id)
				render_401
				return false
			end
			unless current_user.id == @user.id
				render_401
				return false
			end
		end

		if current_user.prof? && (not current_user.admin?)
			unless current_user.all_team_ids.include?(@team.id)
				render_401
				return false
			end
		end
	end

	def show
		@answers = Answer.where(user_id: @user.id, team_id: @team.id, question_id:@question.id).desc(:created_at)
		Log.log_team_user_lo_question_view(current_user.id,@team.id,@user.id,@lo.id,@question.id)
	end
end

app/controllers/panel/teams_controller.rb
class Panel::TeamsController < ApplicationController
	layout "dashboard"
	before_filter :authenticate_user!
	before_filter :get_team

	def get_team
		@team = Team.find(params[:id])
    lo_ids = Answer.where(team_id:@team.id).desc("lo_id").distinct("lo_id")
    if lo_ids.empty?
      @los = @team.los
    else
      @los = Lo.find(lo_ids) | @team.los
    end

 		unless current_user.prof?
			unless current_user.team_ids.include?(@team.id)
				render_401
				return false
			end
		end

		if current_user.prof? && (not current_user.admin?)
			unless current_user.all_team_ids.include?(@team.id)
				render_401
				return false
			end
		end
	end

	def show
    if not current_user.admin? and @team.owner_id != current_user.id
      redirect_to panel_team_user_path(@team, @current_user)
    end

		@recommendations = Recommendation.all_from_team(current_user.id,@team.id)

		Log.log_team_view(current_user.id,@team.id)

    #@chart_data = GraphDataGenerator::team_tries_x_time(@team.id,"daily")
    @recent_activity_data = GraphDataGenerator::team_recent_activity(@team.id)
    @team_lo_tries = GraphDataGenerator::team_lo_tries(@team.id)

    @answers = Answer.where(team_id:@team.id).desc(:id).limit(10)
    # @answers = []
	end
end

app/controllers/panel/users_controller.rb
class Panel::UsersController < ApplicationController
	layout "dashboard"
	before_filter :authenticate_user!
	before_filter :get_data

	def get_data
		@team = Team.find(params[:team_id])
		@user = User.find(params[:id])

    lo_ids = Answer.where(user_id:@user.id, team_id:@team.id).desc("lo_id").distinct("lo_id")
    @los = Lo.find(lo_ids) | @team.los

		unless current_user.prof?
			unless current_user.team_ids.include?(@team.id)
				render_401
				return false
			end
			unless current_user.id == @user.id
				render_401
				return false
			end
		end

		if current_user.prof? && (not current_user.admin?)
			unless current_user.all_team_ids.include?(@team.id)
				render_401
				return false
			end
		end
	end

	def show
    unless @team.users.include?(current_user) || current_user.prof?
      redirect_to dashboard_home_path
    end

		Log.log_team_user_view(current_user.id,@team.id,@user.id)

    @recent_activity_data = GraphDataGenerator::team_user_recent_activity(@team.id,@user.id)
		@team_user_lo_tries = GraphDataGenerator::team_user_lo_tries(@team.id,@user.id)
	end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
	layout "retroaction", :only => [:retroaction]
  layout "dashboard"
	before_filter :authenticate_user!

	def index
		@my_teams = Team.where(owner_id: current_user.id).asc('name')
		@teams = current_user.teams.asc('name')
    @others = Array.new
    if current_user.admin?
      @others = Team.all.asc('name').entries - @my_teams
		end
    @last_comments = Comment.where(target_user_id: current_user.id).desc('created_at')[0..4]
    #@old_teams = Answer.all.distinct('team_id') - Team.all.entries
	end

  def comments
    @comments = Comment.where(target_user_id:current_user.id).desc('created_at')
  end

  def retroaction
    @answer = Answer.find(params[:answer_id])
    @other_answers = Hash.new
    @answer.exercise.questions.each do |q|
      if q.id != @answer.question_id
        @other_answers[q.id] = Hash.new

        #la = LastAnswer.where(user_id: @answer.user_id, question_id: q.id).try(:first)
        
        #if la
        #  @other_answers[q.id] = Answer.find(la.answer_id)
        #else
        #  @other_answers[q.id] = nil
        #end

        @other_answers[q.id][:answer] = Answer.where(user_id: @answer.user_id, question_id: q.id, team_id:@answer.team_id).lte(created_at: @answer.created_at).try(:first)
        @other_answers[q.id][:previous_answers] = (not @other_answers[q.id][:answer].nil?) ? @other_answers[q.id][:answer].previous(5) : []
      end
    end
  end

  def explorer
    
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  respond_to :json
  before_filter :authenticate_user!
  before_filter :teams, except: :enrolled

  def index
    @teams = Team.search(params[:search]).page(params[:page]).per(10).asc('name')
    #p @teams
  end

  def enrolled
    @teams = current_user.teams
  end

  def created
    @teams = @owner_teams.asc(:name)
  end

  def my_teams
    @teams = created | enrolled
  end

  def learners
    if params[:team_id]
      @learners = Team.find(params[:team_id]).users
    else
      @learners = []
      @owner_teams.each {|team| @learners = @learners | team.users}
    end
  end

  def enroll
    @team = Team.find(params[:id])
    if @team.enroll(current_user, params[:code])
      respond_with(@team)
    else
      respond_with(@team, status: 422)
    end
  end

  def show
    #@team = @owner_teams.find(params[:id])
    @team = Team.find(params[:id])
    respond_with(@team)
  end

  def create
    @team = Team.new(params[:team])
    @team.owner_id = current_user.id

    if @team.save
      respond_with(@team)
    else
      respond_with(@team, status: 422)
    end
  end

  def update
    @team = @owner_teams.find(params[:id])

    if @team.update_attributes(params[:team])
      respond_with(@team)
    else
      respond_with(@team, status: 422)
    end
  end

  def destroy
    @team = @owner_teams.find(params[:id])
    @team.destroy
    respond_with(@team)
  end

  def teams_for_search
    if current_user.admin?
      @teams = Team.desc(:created_at)
    else
      my_teams
    end
  end

private
  def teams
    if current_user.super_admin?
      @owner_teams = Team.all
    else
      @owner_teams = Team.where(owner_id: current_user.id)
    end
  end

end

app/views/panel/teams/show.html.erb
<%= content_for :scripts do %>
  <%= javascript_include_tag 'dashboard/resizeApp' %>
  <%= javascript_include_tag 'difflib' %>
  <%= javascript_include_tag 'diffview' %>
  <%= javascript_include_tag 'dashboard/home' %>

  <script type="text/javascript">
    function diffUsingJS(div_id,label1,txt1,label2,txt2){
      // get the baseText and newText values from the two textboxes, and split them into lines
      base = difflib.stringAsLines(txt1);//$("baseText").value);
      newtxt = difflib.stringAsLines(txt2);//$("newText").value);

      //create a SequenceMatcher instance that diffs the two sets of lines
      sm = new difflib.SequenceMatcher(base, newtxt);

      // get the opcodes from the SequenceMatcher instance
      // opcodes is a list of 3-tuples describing what changes should be made to the base text
      // in order to yield the new text
      opcodes = sm.get_opcodes();
      diffoutputdiv = $("#"+div_id);
      while(diffoutputdiv.firstChild)
        diffoutputdiv.removeChild(diffoutputdiv.firstChild);

      //console.log opcodes

      $(diffoutputdiv).append(diffview.buildView({baseTextLines: base, newTextLines: newtxt, opcodes: opcodes, baseTextName: label1, newTextName: label2, contextSize: 0, viewType: 0 }))
    }
  </script>
<% end %>
<div id="answer-show">

</div>
<% if  current_user.admin? or current_user.id == @team.owner_id %>

  <!-- Content Header (Page header) -->
  <section class="content-header">
      <h1>
          Turma - <%= @team.name %>
          <small>Analise o desempenho da sua turma</small>
      </h1>
      <ol class="breadcrumb">
          <li><i class="fa fa-home"></i> <%= link_to "Home", dashboard_home_path %></li>
          <li><i class="fa fa-users active"></i> Turma "<%= @team.name %>"</li>
      </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <div class="row">

      <% unless @team.active %>
        <div class="alert alert-danger">
          Esta turma está desativada.
        </div>
      <% end %>

          <section class="col-lg-6">
            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">Objetos de aprendizagem atualmente disponíveis para esta turma</h3>
                    <div class="box-tools pull-right">
                      <%= link_to edit_dashboard_team_path(@team) do %>
                        <button class="btn btn-primary btn-sm"><i class="fa fa-edit"></i> Editar</button>
                      <% end %>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body shorted-box">
                  <% @team.los.each do |lo| %>
                    <section class="well">
                      <header class="clearfix">
                        <div class="left">
                          <h4><%= link_to lo.name, overview_panel_team_lo_path(@team, lo)%>
                            <% unless @team.lo_ids.include?(lo.id) %>
                              <span class="date-info">(atualmente não disponível para os alunos)</span>
                            <% end %>
                          </h4>
                        </div>
                      </header>
                    </section>

                  <% end %>
              </div>
            </div>

            <div class="box box-solid collapsed-box">
                <div class="box-header">
                    <h3 class="box-title">Objetos de aprendizagem já utilizados nesta turma</h3>
                    <div class="box-tools pull-right">
                      <button class="btn btn-default btn-sm" data-widget="collapse"><i class="fa fa-plus"></i></button>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body" style="display:none;">
                  <% @los.each do |lo| %>
                    <section class="well">
                      <header class="clearfix">
                        <div class="left">
                          <h4><%= link_to lo.name, overview_panel_team_lo_path(@team, lo)%>
                            <% unless @team.lo_ids.include?(lo.id) %>
                              <span class="date-info">(atualmente não disponível para os alunos)</span>
                            <% end %>
                          </h4>
                        </div>
                      </header>
                    </section>

                  <% end %>
              </div>
            </div>

            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">Últimas respostas nesta turma</h3>
                </div><!-- /.box-header -->
                <div class="box-body shorted-box">
                  <% @answers.each do |a| %>
                    <%= answer_link(a) %>
                  <% end %>
              </div>
            </div>

            <% if current_user.prof? %>
            <!-- box  (with bar chart) -->
            <div class="box  box-info">
                <div class="box-header">
                    <!-- tools box  -->
                    <div class="pull-right box-tools">
                        <button class="btn btn-info btn-sm" data-widget='collapse' ><i class="fa fa-minus"></i></button>
                    </div><!-- /. tools -->
                    <i class="fa fa-exclamation"></i>

                    <h3 class="box-title">Recomendações automáticas para você</h3>
                </div><!-- /.box-header -->

                <div class="box-body shorted-box">
                  <% if @recommendations.empty? %>
                    <p class="text-center">
                      Nenhuma recomendação no momento.
                    </p>
                  <% end %>
                  <% unless @recommendations.empty? %>
                    <% @recommendations.each do |recommendation| %>
                      <%= render :partial => "dashboard/recommendation", :locals => {:recommendation => recommendation} %>
                    <% end %>
                  <% end %>
                </div><!-- /.box-body -->
<!--
                <div class="box-footer">
                    <div class="row">
                        <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">

                        </div>
                    </div>
                </div>-->
            </div><!-- /.box  -->
            <% end %>

          </section>

          <section class="col-lg-6">

            <%= recent_activity(@recent_activity_data) %>


            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">Alunos matriculados nesta turma</h3>
                </div><!-- /.box-header -->
                <div class="box-body shorted-box">
                  <table class="table table-hover table-bordered">
                    <tr>
                      <th>Nome</th>
                      <th>Progresso</th>
                    </tr>
                    <% @team.users.sort_by{|x| x.name.downcase}.each do |u| %>

                      <tr>
                        <td><%= link_to u.name, panel_team_user_path(@team, u)%> <small>(<%= u.email %>)</small> <small><%= "(Seu próprio usuário)" if u.id ==current_user.id %></small></td>
                        <td>

                          <%= render_progress(u.progress_team(@team.id),"% concluído","width:100%;") %>

                        </td>
                      </tr>
                    <% end %>
                  </table>
                </div>
            </div>

            <%= pie_chart(@team_lo_tries,"Número de tentativas por O.A.") %>

          </section>
      </div>



  </section>
<% end %>