config/routes.rb
Carrie::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {:sessions => "sessions"}

  scope "api" do
    namespace :published do
      resources :los, only: :show
      match '/teams/:team_id/los/:id' => "los#show"
    end

    resources :comments,only: :index do
    end

    resources :answers do
      post 'retroaction', on: :member
      get 'page/:page', :action => :index, :on => :collection
      resources :comments
    end

    match '/home/lo_example' => "home#lo_example"
    resources :retroaction_answers, only: :create
    resources :contacts, only: :create

    resources :teams do
      get 'created', on: :collection
      get 'enrolled', on: :collection
      get 'my_teams', on: :collection
      get 'teams_for_search', on: :collection
      get 'learners', on: :collection
      post 'enroll', on: :member
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :los do
      get 'my_los', on: :collection
      get 'los_for_search', on: :collection
      get 'exercises', on: :collection
      resources :introductions do
        collection {post :sort}
      end
      resources :exercises do
        delete 'delete_last_answers', :on => :member
        resources :questions do
          resources :tips
          resources :test_cases
          collection {post :sort}
        end
        collection { post :sort }
      end
    end
  end

  #get "answers_panel/index"
  #get "answers_panel/answers"

  namespace :newapi do
    resources :users, :only => [:index]
    resources :answers, :only => [:show] do
      member do
        get "connections"
        get "connected_component"
        get "similar"
      end
      collection do
        post "connections", action: :group_connections
        post "group"
      end
    end
    resources :connections, :only => [:create] do
      member do
        delete "reject_connection"
        put "accept_connection"
      end
    end
  end

  namespace :panel do
    #get "retroaction/:answer_id", :action => :retroaction
    #get "index"
    #get "comments"
    #get "explorer"
    resources :teams, only: [:show] do
      resources :los, only: [] do
        get 'overview', on: :member
      end
      resources :users, only: [:show] do
        resources :los, only: [:show] do
          resources :questions, only: [:show] do
            resources :answers, only: [:show] do
              post 'change_correctness', on: :member
              get 'try_again', on: :member
            end
          end
        end
      end
    end
  end

  #namespace :explorer do
  #  get "index"
  #  get "load_users"
  #  post "info_answer"
  #  post "info_connection"
  #  put "search"
  #  put "fulltext_search"
  #end

  namespace :dashboard do
    get "home"

    get "help"
    get "hide_help"

    post "graph_answer_info"
    post "graph_connection_info"

    get "search"
    get "timeline"
    get "graph"
    get "tags"

    put "fulltext_search/page/:page", action: "fulltext_search", as: "fulltext_search"
    put "timeline_search/page/:page", action: "timeline_search", as: "timeline_search"
    put "graph_search/page/:page", action: "graph_search", as: "graph_search"
    put "tags_search/page/:page", action: "tags_search", as: "tags_search"
    put "tags_search_aat", action: "tags_search_aat", as: "tags_search_aat"

    resources :teams, :only => [:new,:edit,:update,:create,:destroy] do
      post :unenroll, on: :member
    end
    namespace :teams do
      get "available"
      post "enroll"
    end

    namespace :answers do
      get "show"
    end

    namespace :connections do
      get "show"
    end

    resources :messages do
      resources :replies, :only => [:create,:destroy]
    end

    namespace :tags do
      get "show"
      put "add_tag"
      post "create_tag"
      delete "remove_tag"
      put "accept_tag"
      put "reject_tag"
    end
  end

  root to: "welcome#index"

  match '*path', to: 'home#index'
end

app/models/lo.rb
class Lo
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
  field :available, type: Boolean, default: false

  attr_accessible :id, :name, :description, :available

  validates_presence_of :name, :description
  validates :name, uniqueness: true
  validates :available, :inclusion => {:in => [true, false]}

  belongs_to :user
  has_many :introductions, dependent: :delete
  has_many :exercises, dependent: :delete
  has_and_belongs_to_many :teams

  def pages
    self.introductions_avaiable + self.exercises_avaiable
  end

  def pages_count
    self.pages.size
  end

  def pages_with_name
    i, e, page_count = 0, 0, 0

    self.pages.map do |page|
      if page.instance_of? Introduction
        i += 1
        page_count = i
      else
        e += 1
        page_count = e
      end
      { page_name: "#{page.class.model_name.human} #{page_count}: #{page.title}",
        type: page.class.to_s.downcase,
        page_collection: page_count-1
      }
    end
  end

  def exercises_avaiable
    self.exercises.where(available: true)
  end

  def introductions_avaiable
    self.introductions.where(available: true)
  end

end

app/models/team.rb
#encoding: utf-8
class Team
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code, :type => String
  field :name, :type => String
  field :owner_id, :type => Moped::BSON::ObjectId
  field :active, :type => Boolean, :default => true

  attr_accessible :name, :code, :owner_id, :lo_ids, :active

  has_and_belongs_to_many :los
  has_and_belongs_to_many :users

  validates_presence_of :name, :code
  validates_uniqueness_of :name

  # Return scope not the records
  def self.search(search)
    if search
      any_of(:name => /.*#{search}.*/i).desc(:created_at)
    else
      all.desc(:created_at)
    end
  end

  def owner
    @owner ||= User.find(self.owner_id)
  end

  def enroll(user, code)
    if code == self.code
      self.errors.messages.delete :enroll
      unless self.users.include?(user)
        self.users << user
        self.save
      end
      return true
    else
      self.errors.messages[:enroll] = [I18n.translate('mongoid.errors.messages.invalid')]
      return false
    end
  end

  def questions
    questions = []
    unless self.los.empty?
      self.los.each do |lo|
        unless lo.exercises.empty?
          lo.exercises.each do |ex|
            questions += ex.questions
          end
        end
      end
    end
    questions    
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable
  devise :database_authenticatable, :registerable,
	 :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ''
  field :encrypted_password, :type => String, :default => ''

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  index({ email: 1 }, { unique: true, background: true })

  field :name, :type => String
  field :gravatar
  field :admin, :type => Boolean, default: false
  field :prof, :type => Boolean, default: false
  field :super_admin, :type => Boolean, default: false
  field :guest, :type => Boolean, default: false
  field :show_help, :type => Boolean, default: true

  attr_accessible :id, :name, :email, :password, :password_confirmation, :remember_me, :guest, :prof

  validates_presence_of :name

  before_save :do_gravatar_hash

  has_many :los, dependent: :delete
  has_many :answers, dependent: :delete
  has_many :retroaction_answers, dependent: :delete
  has_many :last_answers, dependent: :delete
  has_many :tags, dependent: :delete
  has_many :messages, dependent: :delete
  has_and_belongs_to_many :teams
  has_many :replies, dependent: :delete
  has_many :recommendations, dependent: :delete

  def do_gravatar_hash
    self.gravatar= Digest::MD5.hexdigest(self.email)
  end

  def question_overview(team,question)
    r = Answer.where(user_id: self.id, team_id: team.id, question_id: question.id, correct: true).last
    if r.nil?
      r = Answer.where(user_id: self.id, team_id: team.id, question_id: question.id).last
    end
   # [r,Answer.where(user_id: self.id, team_id: team.id, question_id: question.id).count]
  	[r,Answer.where(user_id: self.id, team_id: team.id, question_id: question.id).count,Comment.where(target_user_id: self.id, question_id:question.id).count]
  end

  def self.guest
    @user ||= User.where(email: 'guest@farma.mat.br').first
    return @user
  end


  def all_teams
    if self.admin?
      Team.all.asc(:name)
    else
      teams = Team.where(owner_id: self.id).asc('name') + self.teams.asc('name')
    end
  end

  def all_team_ids
    if self.admin?
      Team.all.pluck(:id)
    else
      teams = Team.where(owner_id: self.id).pluck(:id)
    end
  end

  def all_questions
    if self.admin?
      Question.all.asc(:title)
    else
      answered_questions = Answer.where(user_id:self.id).desc("question_id").distinct("question_id")
      questions = []
      unless answered_questions.empty?
	questions = Question.find(answered_questions)
      end

      question_ids = []
      for lo in self.all_los
	for ex in lo.exercises
	  question_ids = question_ids + ex.question_ids
	end
      end

      questions = questions + Question.find(question_ids)
      questions.uniq{|x| x.id}.sort_by{|x| x.title}
    end
  end

  def all_los
    if self.admin?
      Lo.all.asc(:name)
    else
      los = Array.new
      for team in self.all_teams do
	lo_ids = Answer.where(team_id:team.id).desc("lo_id").distinct("lo_id")
	if lo_ids.empty?
	  los = los + team.los
	else
	  los = los + (Lo.find(lo_ids) | team.los)
	end
      end

      if self.prof?
	los += self.los
      end

      los.uniq{|x| x.id}.sort_by{:name}
    end
  end

  def all_students
    if self.admin?
      User.all.asc(:name)
    else
      users = [self]
      for team in Team.where(owner_id: self.id).asc('name') do
	users = users + team.users
      end

      users.uniq{|x| x.id}.sort_by{:name}
    end
  end

  def all_tags
    #if self.admin?
      Tag.all.asc(:name)
    #else
    #  self.tags.asc(:name)
    #end
  end

  def number_of_new_messages
    Message.any_of(:new_flag_user_ids => self.id).count + self.messages.keep_if {|x| x['new_flag_user_id'] }.count
  end

	def messages_to_me
	  #@messages = Message.where(:target_user_ids => self.id).desc(:updated_at)
	@messages = Message.any_of({:target_user_ids => self.id}, {:user_ids => self.id.to_s}).desc(:updated_at)
	end

	def last_messages_to_me(n)
	  @messages = Message.any_of({:target_user_ids => self.id}, {:user_ids => self.id.to_s}).desc(:updated_at).desc(:updated_at).to_a + self.messages.keep_if {|x| x['new_flag_user_id'] }
	  @messages.sort { |x,y| y.updated_at <=> x.updated_at}
	end


	def is_message_new?(m)
	  m.new_flag_user_ids.include?(self.id) or (m.user_id == self.id and m.new_flag_user_id)
	end

	def link_to_question(q)
	  self.teams.each do |t|
	    t.los.each do |lo|
	      for i in 0..lo.exercises.length-1 do
	        e = lo.exercises[i]
	        if e.question_ids.include?(q.id)
	          return "/published/teams/#{t.id}/los/#{lo.id}/pages/#{i+1+lo.introductions.count}"
	        end
	      end
	    end
	  end
	  return nil
	end


	def progress_question(team_id,question_id)
	correct = Answer.where(user_id: self.id, question_id:question_id, correct: true).count > 0 ? true : false
if correct
return 1
else
	  Progress.find_or_initialize_by(team_id:team_id,user_id:self.id,question_id:question_id).value
end
	end

	def progress_lo(team_id,lo_id)
	  exercises = Lo.find(lo_id).exercises

	  progress = 0.0
	  n = 0
	  exercises.each do |ex|
	    ex.questions.each do |q|
	      progress = progress + self.progress_question(team_id,q.id)
	      n = n+1
	    end
	  end

	  unless n != 0
	    return 0.0
	  end

	  progress/n
	end

	def progress_team(team_id)
	  team = Team.find(team_id)

	  progress = 0.0
	  n = 0
	  team.los.each do |lo|
	    progress = progress + self.progress_lo(team_id,lo.id)
	    n = n+1
	  end

	  unless n != 0
	    return 0.0
	  end

	  progress/n
	end

	def last_try
	  Answer.where(:user_id => self.id).desc(:created_at).first
	end

	def questions_without_tries()
	  questions = []

	  self.teams.each do |t|
	    t.los.each do |lo|
	      lo.exercises.each do |ex|
	        ex.questions.each do |q|
	          if self.progress_question(t.id,q.id) == 0.0
	            questions << [t,q]
	          end
	        end
	      end
	    end
	  end
	  questions
	end

	def super_admin?
	  if self.super_admin
	    return true
	  end
	  return false
	end

	def admin?
	  if self.super_admin or self.admin
	    return true
	  end
	  return false
	end

	def prof?
	  if self.super_admin or self.admin or self.prof
	    return true
	  end
	  return false
	end

	def student?
	  if self.prof? && (not self.admin?)
	    return false
	  end
	  return true
	end
end

app/controllers/dashboard/answers_controller.rb
class Dashboard::AnswersController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!
  before_filter :can_view

  def can_view
    can = false
    @answer = Answer.find(params[:id])
    @answer.class_eval do
      attr_accessor :filter_names
    end

    @answer.filter_names = false

    if current_user.admin?
      can = true
    end

    if params.has_key?(:message_id)
      m = Message.find(params[:message_id])

      if m.target_user_ids.include?(current_user.id) and m.answer_ids.include?(params[:id])
        can = true

        @answer.filter_names = true
      end
    end

    if @answer.user_id == current_user.id
      can = true
    end

    if current_user.prof?
      if current_user.id.to_s == @answer.team.owner_id.to_s
        can = true
      end
    end


    unless can
      render :file => "public/401.html", :status => :unauthorized
    end
  end

  def show
    @available_tags = @answer.available_tags
    @answer.class_eval do
      attr_accessor :from_graph
    end

    if params.has_key?(:graph)
      @answer.from_graph = true
    else
      @answer.from_graph = false
    end

    Log.log_answer_view_simple(current_user.id,@answer.id)
  end

end

app/controllers/dashboard/connections_controller.rb
class Dashboard::ConnectionsController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!
  before_filter :can_view


  def can_view
    @connection = Connection.find(params[:id])
    @answer1 = Answer.find(@connection.answer_id)
    @answer2 = Answer.find(@connection.target_answer_id)

    can = false

    if current_user.admin?
      can = true
    end

    if @answer1.user_id == current_user.id && @answer2.user_id == current_user.id
      can = true
    end

    if current_user.prof?
      if @answer1.team.owner_id.to_s == current_user.id.to_s && @answer2.team.owner_id.to_s == current_user.id.to_s
        can = true
      end
    end

    unless can
      render_401
    end
  end

  def show
    Log.log_connection_view_simple(current_user.id,@connection.id)
  end
end

app/controllers/dashboard/replies_controller.rb
class Dashboard::RepliesController < ApplicationController
  layout "dashboard"

  before_filter :authenticate_user!
  before_filter :get_message
  before_filter :can_post, :only => [:create]
  before_filter :can_delete, :only => [:delete]

  def get_message
    @message = Message.find(params[:message_id])
  end

  def can_post
    if (not @message.user_id == current_user.id) and (not @message.target_user_ids.include?(current_user.id.to_s))
      render_401
    end
  end

  def can_delete
    unless @message.user_id == current_user.id
      render_401
    end
  end

  def create

    @reply = Reply.new(params[:reply])

    @reply.user_id = current_user.id
    @reply.message_id = @message.id

    respond_to do |format|
      if @reply.save
        if @message.target_user_ids.nil? or @message.target_user_ids.empty?
          @message.new_flag_user_ids = @message.user_ids
        else
          @message.new_flag_user_ids = @message.target_user_ids
        end
        @message.save!
        format.html { redirect_to dashboard_message_path(@message), notice: 'Mensagem criada com sucesso.' }
        format.json { render json: @reply, status: :created, location: @message }
      else
        format.html { render "dashboard/messages/show" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_message_path(@message) }
      format.json { head :no_content }
    end
  end

end

app/views/dashboard/_filter_in_words.html.erb
<p>
<% if params.has_key?(:query) and not params[:query].empty? %>
  <b>Palavra-chave:</b>
    "<%= params[:query] %>";
<% end %>

<% if params.has_key?(:daterange) and not params[:daterange].empty? %>
  <% start_date = DateTime.strptime(params[:daterange].split(" - ").first,"%d/%m/%Y %H:%M").change(:offset => "-0300")  %>
  <% end_date = DateTime.strptime(params[:daterange].split(" - ").last,"%d/%m/%Y %H:%M").change(:offset => "-0300") %>
<b>Data início: </b>
    <%= start_date %>
<b>Data final: </b>
    <%= end_date %>;
<% end %>

<% if params.has_key?(:user_ids) %>
  <b>Usuários: </b> [
  <% User.find(params[:user_ids]).each do |u| %>
    "<%= u.name %>",
  <% end %>
  ];
<% end %>

<% if params.has_key?(:team_ids) %>
  <b>Turmas: </b> [
    <% Team.find(params[:team_ids]).each do |t| %>
    "<%= t.name %>",
    <% end %>
    ];
<% end %>

<% if params.has_key?(:lo_ids) %>
<b>O.A.'s: </b> [
  <% Lo.find(params[:lo_ids]).each do |lo| %>
  "<%= lo.name %>",
  <% end %>
  ];
<% end %>

<% if params.has_key?(:question_ids) %>
  <b>Questões: </b> [
    <% Question.find(params[:question_ids]).each do |q| %>
    "<%= q.title %>",
    <% end %>
    ];
<% end %>

<% if params.has_key?(:tag_ids) %>
  <b>Tags: </b> [
    <% Tag.find(params[:tag_ids]).each do |t| %>
    "<%= t.name %>",
    <% end %>
    ];
<% end %>
</p>

app/views/dashboard/_graph_search_result.html.erb
<div class="row">
  <div class="col-md-12 text-center" style="margin-bottom:20px;">
    <%= total %> respostas encontradas.
    <% if total > 50 %>
      Mostrando apenas as 50 mais recentes.
    <% end %>
    <%= filter_in_words(@params) %>
      <% if as.count > 0 %>


        <%= button_tag raw("<i class='fa fa-plus'></i> Adicionar todas as respostas encontradas"), :class => "btn btn-small btn-warning", :id => "add-all" %>
        <table class="table table-hover">
          <tr>
            <th></th>
            <th>Aluno</th>
            <th>Questão</th>
            <th>Turma</th>
            <th>O.A.</th>
            <th>Tentativa</th>
            <th>Data</th>
            <th>

            </th>
          </tr>
          <% i = 0 %>
          <% as.each do |a| %>

            <% if a.correct %>
              <tr class="success answer" data-answer-id="<%= a.id %>">
            <% else %>
              <tr class="danger  answer" data-answer-id="<%= a.id %>">
            <% end %>

              <td>
                <img src="http://www.gravatar.com/avatar/<%= a.user.gravatar %>?s=35" class="img-circle" alt="Imagem do Usuário" />
              </td>
              <td>
                <%= a.user.name %>
              </td>
              <td>
                <%= a.question.title %>
              </td>
              <td>
                <%= a.team.name %>
              </td>
              <td>
                <%= a.lo.name %>
              </td>
              <td>
                #<%= a.try_number %>
              </td>
              <td>
                <small>Realizada em <b><%= a.created_at.strftime("%d/%m/%Y às %H:%M:%S") %></b></small>
              </td>
              <td>
                <%= button_tag raw("<i class='fa fa-plus'></i> Adicionar resposta"), :class => "btn btn-small btn-primary add-answer btn-block", :data => {:id => a.id.to_s} %>
                <%= button_tag raw("<i class='fa fa-plus'></i> Adicionar respostas semelhantes"), :class => "btn btn-small btn-block btn-warning add-similar", :data => {:id => a.id.to_s} %>
                <%= button_tag raw("<i class='fa fa-plus'></i> Adicionar componente conexa"), :class => "btn btn-small btn-block btn-danger add-connected-component", :data => {:id => a.id.to_s} %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboard/_paginator.html.erb
<% if !as.blank? %>
  <% for i in 1..as.num_pages %>
    <% if i == as.current_page %>
      <%= " #{i.to_s} " %>
    <% else %>
      <a href="#" class="search-page" data-path="<%= dashboard_fulltext_search_path(page: i)%>"><%= " #{i.to_s} " %></a>
    <% end %>
  <% end %>
<% else %>

<% end %>

app/views/dashboard/_tags_search_result.html.erb
<div id="answer-show"></div>

<div class="row">
  <div class="col-md-12" style="margin-bottom:20px;">
    <h3>Confirmadas<small> <%= total %> respostas encontradas <%= raw " (Mostrando apenas as 50 mais recentes)" if total > 50 %>.</small></h3>
    <%= filter_in_words(@params) %>
  </div>
</div>

<div class="row">
  <div class="col-md-12" style="margin-bottom:20px;" id="confirmed-tags">
    <%= render :partial => "dashboard/answers/answer_card", :locals => {:answers => as, :button_tag => false, :n => 3} %>
  </div>
</div>

<div class="row">
  <div class="col-md-12" style="margin-bottom:20px;">
    <h3>Atribuídas automaticamente</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12" style="margin-bottom:20px;">

    <%= link_to "Atualizar", dashboard_tags_search_aat_path(@params), :class=>"btn btn-default", :remote => true, :method => :put %>

    <div id="aat">

    </div>

  </div>
</div>

app/views/dashboard/search_result.js.erb
$("#search_result").html("<%= escape_javascript(render(:partial => 'search_result', :locals => {:as => @as, :button_add => @button_add}))%>");

var i=0;

$('.answer').each(function() {
	$(this).hide();
});

$('.answer').each(function() {
	$(this).delay((i++)*50).fadeIn();
});

$(".answer-btn").click(function(){
  $.ajax({
    url: "/dashboard/answers/show",
    data: {
      id: $(this).data("id")
    },
    type: "get"
  });
});

$("form.search-bar").attr("action",$("form.search-bar").data("original-path"));

$("span.label").tooltip();

if(searchResultCallback && typeof(searchResultCallback) == "function")
  searchResultCallback();

app/views/dashboard/tags.html.erb
<%= content_for :scripts do %>
    <%= javascript_include_tag 'dashboard/resizeApp' %>
    <%= javascript_include_tag 'difflib' %>
    <%= javascript_include_tag 'diffview' %>
    <%= javascript_include_tag 'dashboard/tags' %>


  <script type="text/javascript">
  function diffUsingJS(div_id,label1,txt1,label2,txt2){
    // get the baseText and newText values from the two textboxes, and split them into lines
    base = difflib.stringAsLines(txt1);//$("baseText").value);
    newtxt = difflib.stringAsLines(txt2);//$("newText").value);

    //create a SequenceMatcher instance that diffs the two sets of lines
    sm = new difflib.SequenceMatcher(base, newtxt);

    // get the opcodes from the SequenceMatcher instance
    // opcodes is a list of 3-tuples describing what changes should be made to the base text
    // in order to yield the new text
    opcodes = sm.get_opcodes();
    diffoutputdiv = $("#"+div_id);
    while(diffoutputdiv.firstChild)
      diffoutputdiv.removeChild(diffoutputdiv.firstChild);

    //console.log opcodes

    $(diffoutputdiv).append(diffview.buildView({baseTextLines: base, newTextLines: newtxt, opcodes: opcodes, baseTextName: label1, newTextName: label2, contextSize: 0, viewType: 0 }))
  }
  </script>
<% end %>

<%= content_for :stylesheets do %>
    <%= stylesheet_link_tag    'dashboard/tags', :media => 'all' %>
<% end %>

<div id="answer-show">

</div>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Tags
        <small>Manipule as categorias de resposta</small>
    </h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-home"></i> <%= link_to "Home", dashboard_home_path %></li>
        <li class="active"><i class="fa fa-tags"></i> Tags</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div style="margin-bottom:20px;" class="col-md-12">
            <p>
            <% @tags.sort.each do |t| %>
              <%= render_tag(t,true) %>
            <% end %>
            </p>
            <hr>
            <h2 class="tags-header"></h2>
        </div>
    </div>


    <div class="row" id="tags-body">
        <div style="margin-bottom:20px;" class="col-md-10 col-md-offset-1">
           <%= render(:partial => 'search_bar', :locals => { :form_id => "search-form", :path => dashboard_tags_search_path(page:1) }) %>
           <%= render(:partial => 'search_filters', :locals => { :form_id => "search-form", :users => @users, :teams => @teams, :los => @los, :questions => @questions, :tags => @tags }) %>
        </div>
    </div>

            <div id="search_result">

            </div>


</section><!-- /.content -->

app/views/dashboard/timeline.html.erb
<%= content_for :scripts do %>
    <%= javascript_include_tag 'dashboard/resizeApp' %>
    <%= javascript_include_tag 'difflib' %>
    <%= javascript_include_tag 'diffview' %>
    <%= javascript_include_tag 'dashboard/tags' %>


  <script type="text/javascript">
  var graph=null;
  function diffUsingJS(div_id,label1,txt1,label2,txt2){
    // get the baseText and newText values from the two textboxes, and split them into lines
    base = difflib.stringAsLines(txt1);//$("baseText").value);
    newtxt = difflib.stringAsLines(txt2);//$("newText").value);

    //create a SequenceMatcher instance that diffs the two sets of lines
    sm = new difflib.SequenceMatcher(base, newtxt);

    // get the opcodes from the SequenceMatcher instance
    // opcodes is a list of 3-tuples describing what changes should be made to the base text
    // in order to yield the new text
    opcodes = sm.get_opcodes();
    diffoutputdiv = $("#"+div_id);
    while(diffoutputdiv.firstChild)
      diffoutputdiv.removeChild(diffoutputdiv.firstChild);

    //console.log opcodes

    $(diffoutputdiv).append(diffview.buildView({baseTextLines: base, newTextLines: newtxt, opcodes: opcodes, baseTextName: label1, newTextName: label2, contextSize: 0, viewType: 0 }))


  }
    var timeline = true;
  </script>
<% end %>

<div id="answer-show">

</div>
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Linha do Tempo
        <small>Analise as respostas ao longo do tempo</small>
    </h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-home"></i> <%= link_to "Home", dashboard_home_path %></li>
        <li class="active"><i class="fa fa-clock-o"></i> Linha do Tempo</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div style="margin-bottom:20px;" class="col-md-10 col-md-offset-1">
           <%= render(:partial => 'search_bar', :locals => { :form_id => "search-form", :path => dashboard_timeline_search_path(page:1) }) %>
           <%= render(:partial => 'search_filters', :locals => { :form_id => "search-form", :users => @users, :teams => @teams, :los => @los, :questions => @questions, :tags => @tags }) %>
        </div>
    </div>

	<!-- row -->
	<div class="row">
	    <div id="timelinee" class="col-md-12">

	    </div><!-- /.col -->
	</div><!-- /.row -->
</section><!-- /.content -->