config/routes.rb
Carrie::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {:sessions => "sessions"}

  scope "api" do
    namespace :published do
      resources :los, only: :show
      match '/teams/:team_id/los/:id' => "los#show"
    end

    resources :comments,only: :index do
    end

    resources :answers do
      post 'retroaction', on: :member
      get 'page/:page', :action => :index, :on => :collection
      resources :comments
    end

    match '/home/lo_example' => "home#lo_example"
    resources :retroaction_answers, only: :create
    resources :contacts, only: :create

    resources :teams do
      get 'created', on: :collection
      get 'enrolled', on: :collection
      get 'my_teams', on: :collection
      get 'teams_for_search', on: :collection
      get 'learners', on: :collection
      post 'enroll', on: :member
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :los do
      get 'my_los', on: :collection
      get 'los_for_search', on: :collection
      get 'exercises', on: :collection
      resources :introductions do
        collection {post :sort}
      end
      resources :exercises do
        delete 'delete_last_answers', :on => :member
        resources :questions do
          resources :tips
          resources :test_cases
          collection {post :sort}
        end
        collection { post :sort }
      end
    end
  end

  #get "answers_panel/index"
  #get "answers_panel/answers"

  namespace :newapi do
    resources :users, :only => [:index]
    resources :answers, :only => [:show] do
      member do
        get "connections"
        get "connected_component"
        get "similar"
      end
      collection do
        post "connections", action: :group_connections
        post "group"
      end
    end
    resources :connections, :only => [:create] do
      member do
        delete "reject_connection"
        put "accept_connection"
      end
    end
  end

  namespace :panel do
    #get "retroaction/:answer_id", :action => :retroaction
    #get "index"
    #get "comments"
    #get "explorer"
    resources :teams, only: [:show] do
      resources :los, only: [] do
        get 'overview', on: :member
      end
      resources :users, only: [:show] do
        resources :los, only: [:show] do
          resources :questions, only: [:show] do
            resources :answers, only: [:show] do
              post 'change_correctness', on: :member
              get 'try_again', on: :member
            end
          end
        end
      end
    end
  end

  #namespace :explorer do
  #  get "index"
  #  get "load_users"
  #  post "info_answer"
  #  post "info_connection"
  #  put "search"
  #  put "fulltext_search"
  #end

  namespace :dashboard do
    get "home"

    get "help"
    get "hide_help"

    post "graph_answer_info"
    post "graph_connection_info"

    get "search"
    get "timeline"
    get "graph"
    get "tags"

    put "fulltext_search/page/:page", action: "fulltext_search", as: "fulltext_search"
    put "timeline_search/page/:page", action: "timeline_search", as: "timeline_search"
    put "graph_search/page/:page", action: "graph_search", as: "graph_search"
    put "tags_search/page/:page", action: "tags_search", as: "tags_search"
    put "tags_search_aat", action: "tags_search_aat", as: "tags_search_aat"

    resources :teams, :only => [:new,:edit,:update,:create,:destroy] do
      post :unenroll, on: :member
    end
    namespace :teams do
      get "available"
      post "enroll"
    end

    namespace :answers do
      get "show"
    end

    namespace :connections do
      get "show"
    end

    resources :messages do
      resources :replies, :only => [:create,:destroy]
    end

    namespace :tags do
      get "show"
      put "add_tag"
      post "create_tag"
      delete "remove_tag"
      put "accept_tag"
      put "reject_tag"
    end
  end

  root to: "welcome#index"

  match '*path', to: 'home#index'
end

app/models/exercise.rb
class Exercise
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :content, type: String
  field :available, type: Boolean, default: false
  field :position, type: Integer

  default_scope desc(:position)
  #default_scope order_by([:position, :desc])

  before_create :set_position

  attr_accessible :id, :title, :content, :available, :questions_attributes

  validates_presence_of :title, :content
  validates :available, :inclusion => {:in => [true, false]}

  belongs_to :lo

  has_many :questions, dependent: :delete

  def delete_last_answers_of(user_id)
    self.questions.each  do |question|
      question.last_answers.where(user_id: user_id).try(:delete_all)
      question.tips_counts.where(user_id: user_id).try(:delete_all)
    end
  end

  def questions_avaiable
    self.questions.where(available: true)
  end

private
  def set_position
    self.position = Time.now.to_i
  end
end

app/models/lo.rb
class Lo
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
  field :available, type: Boolean, default: false

  attr_accessible :id, :name, :description, :available

  validates_presence_of :name, :description
  validates :name, uniqueness: true
  validates :available, :inclusion => {:in => [true, false]}

  belongs_to :user
  has_many :introductions, dependent: :delete
  has_many :exercises, dependent: :delete
  has_and_belongs_to_many :teams

  def pages
    self.introductions_avaiable + self.exercises_avaiable
  end

  def pages_count
    self.pages.size
  end

  def pages_with_name
    i, e, page_count = 0, 0, 0

    self.pages.map do |page|
      if page.instance_of? Introduction
        i += 1
        page_count = i
      else
        e += 1
        page_count = e
      end
      { page_name: "#{page.class.model_name.human} #{page_count}: #{page.title}",
        type: page.class.to_s.downcase,
        page_collection: page_count-1
      }
    end
  end

  def exercises_avaiable
    self.exercises.where(available: true)
  end

  def introductions_avaiable
    self.introductions.where(available: true)
  end

end

app/models/tag.rb
# encoding: utf-8
class Tag
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :description
  field :type, type: Integer
  field :primary, type: Boolean, default: false

  belongs_to :user
  has_and_belongs_to_many :answers

  def self.create_primary
    Tag.create(:primary => true,
                            :description => "Erro de compilação - Identificado automaticamente",
                            :type => 2,
                            :name => "Compilação")
    Tag.create(:primary => true,
                            :description => "Erro de saída - Identificado automaticamente",
                            :type => 1,
                            :name => "Saída")
    Tag.create(:primary => true,
                            :description => "Tempo excedido - Identificado automaticamente",
                            :type => 1,
                            :name => "Tempo")
    Tag.create(:primary => true,
                            :description => "Erro de execução - Identificado automaticamente",
                            :type => 1,
                            :name => "Execução")
    Tag.create(:primary => true,
                            :description => "Erro de apresentação - Identificado automaticamente",
                            :type => 1,
                            :name => "Apresentação")
    Tag.create(:primary => true,
                            :description => "Resposta correta",
                            :type => 3,
                            :name => "Correta")
  end

  def self.apply_primary(answer)
    output = []
    # get the primary tags
    compile_error = Tag.find_or_create_by(:primary => true,
                            :description => "Erro de compilação - Identificado automaticamente",
                            :type => 2,
                            :name => "Compilação")
    diff_error = Tag.find_or_create_by(:primary => true,
                            :description => "Erro de saída - Identificado automaticamente",
                            :type => 1,
                            :name => "Saída")
    time_error = Tag.find_or_create_by(:primary => true,
                            :description => "Tempo excedido - Identificado automaticamente",
                            :type => 1,
                            :name => "Tempo")
    exec_error = Tag.find_or_create_by(:primary => true,
                            :description => "Erro de execução - Identificado automaticamente",
                            :type => 1,
                            :name => "Execução")
    presentation_error = Tag.find_or_create_by(:primary => true,
                            :description => "Erro de apresentação - Identificado automaticamente",
                            :type => 1,
                            :name => "Apresentação")
    correct = Tag.find_or_create_by(:primary => true,
                            :description => "Resposta correta",
                            :type => 3,
                            :name => "Correta")

    if not answer.correct
      if answer.compile_errors
        output << compile_error.id.to_s
      else
        answer.results.each do |k,v|
          if  v['diff_error']
            output << diff_error.id.to_s unless output.include?(diff_error.id.to_s)
          elsif v['time_error']
            output << time_error.id.to_s unless output.include?(time_error.id.to_s)
          elsif v['exec_error']
            output << exec_error.id.to_s unless output.include?(exec_error.id.to_s)
          elsif v['presentation_error']
            output << presentation_error.id.to_s unless output.include?(presentation_error.id.to_s)
          end
        end
      end
    else
      output << correct.id.to_s
    end
    output
  end

def self.correct
    compile_error = Tag.where(:primary => true,
                            :description => "Erro de compilao - Identificado automaticamente",
                            :type => 2,
                            :name => "Compilao").first
compile_error.name = "Compilação"
compile_error.description = "Erro de compilação - Identificado automaticamente"
compile_error.save!
end

end

app/models/team.rb
#encoding: utf-8
class Team
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code, :type => String
  field :name, :type => String
  field :owner_id, :type => Moped::BSON::ObjectId
  field :active, :type => Boolean, :default => true

  attr_accessible :name, :code, :owner_id, :lo_ids, :active

  has_and_belongs_to_many :los
  has_and_belongs_to_many :users

  validates_presence_of :name, :code
  validates_uniqueness_of :name

  # Return scope not the records
  def self.search(search)
    if search
      any_of(:name => /.*#{search}.*/i).desc(:created_at)
    else
      all.desc(:created_at)
    end
  end

  def owner
    @owner ||= User.find(self.owner_id)
  end

  def enroll(user, code)
    if code == self.code
      self.errors.messages.delete :enroll
      unless self.users.include?(user)
        self.users << user
        self.save
      end
      return true
    else
      self.errors.messages[:enroll] = [I18n.translate('mongoid.errors.messages.invalid')]
      return false
    end
  end

  def questions
    questions = []
    unless self.los.empty?
      self.los.each do |lo|
        unless lo.exercises.empty?
          lo.exercises.each do |ex|
            questions += ex.questions
          end
        end
      end
    end
    questions    
  end
end

app/controllers/dashboard/answers_controller.rb
class Dashboard::AnswersController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!
  before_filter :can_view

  def can_view
    can = false
    @answer = Answer.find(params[:id])
    @answer.class_eval do
      attr_accessor :filter_names
    end

    @answer.filter_names = false

    if current_user.admin?
      can = true
    end

    if params.has_key?(:message_id)
      m = Message.find(params[:message_id])

      if m.target_user_ids.include?(current_user.id) and m.answer_ids.include?(params[:id])
        can = true

        @answer.filter_names = true
      end
    end

    if @answer.user_id == current_user.id
      can = true
    end

    if current_user.prof?
      if current_user.id.to_s == @answer.team.owner_id.to_s
        can = true
      end
    end


    unless can
      render :file => "public/401.html", :status => :unauthorized
    end
  end

  def show
    @available_tags = @answer.available_tags
    @answer.class_eval do
      attr_accessor :from_graph
    end

    if params.has_key?(:graph)
      @answer.from_graph = true
    else
      @answer.from_graph = false
    end

    Log.log_answer_view_simple(current_user.id,@answer.id)
  end

end

app/controllers/dashboard/connections_controller.rb
class Dashboard::ConnectionsController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!
  before_filter :can_view


  def can_view
    @connection = Connection.find(params[:id])
    @answer1 = Answer.find(@connection.answer_id)
    @answer2 = Answer.find(@connection.target_answer_id)

    can = false

    if current_user.admin?
      can = true
    end

    if @answer1.user_id == current_user.id && @answer2.user_id == current_user.id
      can = true
    end

    if current_user.prof?
      if @answer1.team.owner_id.to_s == current_user.id.to_s && @answer2.team.owner_id.to_s == current_user.id.to_s
        can = true
      end
    end

    unless can
      render_401
    end
  end

  def show
    Log.log_connection_view_simple(current_user.id,@connection.id)
  end
end

app/controllers/dashboard/replies_controller.rb
class Dashboard::RepliesController < ApplicationController
  layout "dashboard"

  before_filter :authenticate_user!
  before_filter :get_message
  before_filter :can_post, :only => [:create]
  before_filter :can_delete, :only => [:delete]

  def get_message
    @message = Message.find(params[:message_id])
  end

  def can_post
    if (not @message.user_id == current_user.id) and (not @message.target_user_ids.include?(current_user.id.to_s))
      render_401
    end
  end

  def can_delete
    unless @message.user_id == current_user.id
      render_401
    end
  end

  def create

    @reply = Reply.new(params[:reply])

    @reply.user_id = current_user.id
    @reply.message_id = @message.id

    respond_to do |format|
      if @reply.save
        if @message.target_user_ids.nil? or @message.target_user_ids.empty?
          @message.new_flag_user_ids = @message.user_ids
        else
          @message.new_flag_user_ids = @message.target_user_ids
        end
        @message.save!
        format.html { redirect_to dashboard_message_path(@message), notice: 'Mensagem criada com sucesso.' }
        format.json { render json: @reply, status: :created, location: @message }
      else
        format.html { render "dashboard/messages/show" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_message_path(@message) }
      format.json { head :no_content }
    end
  end

end

app/controllers/dashboard/teams_controller.rb
class Dashboard::TeamsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_prof, :only =>[:new, :update, :edit, :create,:destroy]
  before_filter :can_edit?, :only =>[:update, :edit, :destroy]

  layout "dashboard"

  def can_edit?
    unless current_user.id.to_s == Team.find(params[:id]).owner_id.to_s || current_user.admin?
      render_401
    end
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    @team.owner_id = current_user.id
    respond_to do |format|
      if @team.save
        format.html { redirect_to dashboard_teams_available_path, notice: 'Turma criada com sucesso.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to panel_team_path(@team.id), notice: 'Turma atualizada com sucesso.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def enroll
    t = Team.find(params[:team][:id])
    unless t.users.include?(current_user)
      if t.code == params[:password]
        t.users << current_user

        t.save!
      else
        @wrong_code_team_id = t.id
      end
    end
    #@teams = Team.all
    @teams = Team.where(active: true)

    render "available"
  end

  def unenroll
    @team = Team.find(params[:id])

    if @team.users.include?(current_user)
      @team.user_ids = @team.user_ids - [current_user.id]
      @team.save!
    end

    redirect_to dashboard_teams_available_path
  end

  def destroy
    @team = Team.find(params[:id])

    if @team.owner_id == current_user.id
      @team.destroy
    end

    redirect_to dashboard_teams_available_path
  end

  def available
    @teams = Team.where(active: true)
    @teams_unavailable = Team.where(active: false)
  end

end

app/views/dashboard/messages/show.html.erb
<%= content_for :scripts do %>
    <%= javascript_include_tag 'dashboard/resizeApp' %>
    <%= javascript_include_tag 'difflib' %>
    <%= javascript_include_tag 'diffview' %>

  <script type="text/javascript">
  function diffUsingJS(div_id,label1,txt1,label2,txt2){
    // get the baseText and newText values from the two textboxes, and split them into lines
    base = difflib.stringAsLines(txt1);//$("baseText").value);
    newtxt = difflib.stringAsLines(txt2);//$("newText").value);

    //create a SequenceMatcher instance that diffs the two sets of lines
    sm = new difflib.SequenceMatcher(base, newtxt);

    // get the opcodes from the SequenceMatcher instance
    // opcodes is a list of 3-tuples describing what changes should be made to the base text
    // in order to yield the new text
    opcodes = sm.get_opcodes();
    diffoutputdiv = $("#"+div_id);
    while(diffoutputdiv.firstChild)
      diffoutputdiv.removeChild(diffoutputdiv.firstChild);

    //console.log opcodes

    $(diffoutputdiv).append(diffview.buildView({baseTextLines: base, newTextLines: newtxt, opcodes: opcodes, baseTextName: label1, newTextName: label2, contextSize: 0, viewType: 0 }))
  }

  var availableUsers = <%= raw @available_users.to_json %>;

  </script>
  <%= javascript_include_tag 'dashboard/messages' %>
<% end %>

<div id="answer-show">

</div>

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Mensagens
        <small>Envie mensagens com recomendações para alunos</small>
    </h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-home"></i> <%= link_to "Home", dashboard_home_path %></li>
        <li><i class="fa fa-envelope"></i> <%= link_to "Mensagens", dashboard_messages_path %></li>
        <li class="active"><i class="fa fa-eye"></i> <%= truncate(@message.subject) %></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-12">


          <div class="box box-solid">
                                <div class="box-header">
                                    <h3 class="box-title">Mensagem de <%= @message.user.name %></h3>
                                    <div class="box-tools pull-right">
                                      <% if @message.has_recommendation? %>
                                        <i class="fa fa-paperclip"></i>
                                      <% end %>
                                    </div>
                                </div>
                                <div class="box-body">


    <div class="row">
        <div class="col-md-12">

            <div class="form-group">
              <%= label_tag "Destinatários" %><br />
              <div>
                <ul id="users">
                  <% unless @message.user_ids.nil? %>
                    <% @message.user_ids.each do |user_id| %>
			<% if @message.user_id == current_user.id or user_id == current_user.id.to_s %>
                        <li data-id="user_id-<%=user_id%>"><%= User.find(user_id).name %></li>
                      <% end %>
                    <% end %>
                  <% end %>
                  <% unless @message.team_ids.nil? %>
                    <% @message.team_ids.each do |team_id| %>
                      <li data-id="team_id-<%=team_id%>">Turma: <%= Team.find(team_id).name %></li>
                    <% end %>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="form-group">
              <%= label_tag "Respostas recomendadas" %><br />
              <ul id="answers">
                  <% unless @message.answer_ids.nil? %>
                    <% i = 1 %>
                    <% @message.answer_ids.each do |answer_id| %>
                      <% a = Answer.find(answer_id) %>
                      <li data-id="answer_id-<%=answer_id%>">
                        <% if current_user.prof? %>
                            <%= a.user.name + " @ " + a.question.title + " #"+ a.try_number.to_s %>
                        <% else %>
                            Resposta <%= raw i.to_s %>
                        <% end %>
                        <% i = i+1 %>
                        <span class='label label-default answer-btn' style='cursor:pointer;' data-id="<%= a.id %>" data-message-id="<%= @message.id %>"> <i class='fa fa-eye'></i></span>
                      </li>
                    <% end %>
                  <% end %>
              </ul>
            </div>
            <div class="form-group">
              <%= label_tag "Questões recomendadas" %><br />
              <ul id="questions">
                  <% unless @message.question_ids.nil? %>
                    <% @message.question_ids.each do |question_id| %>
                      <li data-id="question_id-<%=question_id%>">
                        <a href="<%= current_user.link_to_question(Question.find(question_id)) %>">
                          <%= Question.find(question_id).title %>
                        </a>
                      </li>
                    <% end %>
                  <% end %>
              </ul>
            </div>

        </div>
    </div>

    <div class="row">
        <div style="margin-bottom:20px;" class="col-md-12">
            <hr>


              <h4><%= simple_format @message.subject %></h4>



              <%= simple_format @message.content %>

      </div>
    </div>

    </div><!-- /.box-body -->
  </div>
  </div>
</div>



      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <h3>Comentários</h3>
          <% @message.replies.each do |r| %>
            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title" style="width:80%;">
                      <div class="pull-left image">
                          <img src="http://www.gravatar.com/avatar/<%= r.user.gravatar%>" class="img-circle" alt="Imagem do usuário" style="width:50px;margin-right:10px;"/>
                      </div>
                      <%= r.user.name %>
                      <br><small><i class="fa fa-clock-o"></i> há <%= time_ago_in_words r.updated_at %></small>
                    </h3>
                    <% if @message.user.id == current_user.id %>
                      <div class="box-tools pull-right">
                        <%= link_to dashboard_message_reply_path(@message,r), method: :delete,data: { confirm: 'Você tem certeza que deseja apagar este comentário?'} do %>
                          <%= button_tag "Apagar", :class => "btn btn-sm btn-danger" %>
                        <% end %>
                      </div>

                    <% end %>
                </div>
                <div class="box-body">
                    <%= simple_format r.content %>
                </div><!-- /.box-body -->
            </div>
          <% end %>

          <% if @message.can_post?(current_user) %>
            <div class="box box-solid">
                <div class="box-header">
                    <h3 class="box-title">
                      <div class="pull-left image">
                          <img src="http://www.gravatar.com/avatar/<%= current_user.gravatar%>" class="img-circle" alt="Imagem do usuário" style="width:50px;margin-right:10px;"/>
                      </div>
                      Novo comentário de <%= current_user.name %>
                    </h3>
                </div>
                <div class="box-body">
                    <%= form_tag dashboard_message_replies_path(@message), :method => :post do %>
                      <% if @reply.errors.any? %>
                        <div class="panel panel-danger">
                          <div class="panel-heading">
                            Não pode ser salvo devido à <%= pluralize(@reply.errors.count, "erro")%>:
                          </div>

                          <div class="panel-body">
                            <ul>
                            <% @reply.errors.messages.each do |msg| %>
                              <li><%= msg[1][0] %></li>
                            <% end %>
                            </ul>
                          </div>
                        </div>
                      <% end %>

                      <div class="form-group">
                        <%= label_tag "Comentário" %><br />
                        <%= text_area_tag "reply[content]", @reply.content, :class => "form-control input", :placeholder => "Seu comentário ...", :rows => "8" %>
                      </div>
                      <div class="form-group">
                        <%= button_tag "Enviar", :type => :submit, :class => "btn btm-sm btn-primary" %>
                      </div>
                  <% end %>
                </div><!-- /.box-body -->
            </div>
          <% end %>

        </div>
      </div>

</section>