config/routes.rb
Carrie::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => {:sessions => "sessions"}

  scope "api" do
    namespace :published do
      resources :los, only: :show
      match '/teams/:team_id/los/:id' => "los#show"
    end

    resources :comments,only: :index do
    end

    resources :answers do
      post 'retroaction', on: :member
      get 'page/:page', :action => :index, :on => :collection
      resources :comments
    end

    match '/home/lo_example' => "home#lo_example"
    resources :retroaction_answers, only: :create
    resources :contacts, only: :create

    resources :teams do
      get 'created', on: :collection
      get 'enrolled', on: :collection
      get 'my_teams', on: :collection
      get 'teams_for_search', on: :collection
      get 'learners', on: :collection
      post 'enroll', on: :member
      get 'page/:page', :action => :index, :on => :collection
    end

    resources :los do
      get 'my_los', on: :collection
      get 'los_for_search', on: :collection
      get 'exercises', on: :collection
      resources :introductions do
        collection {post :sort}
      end
      resources :exercises do
        delete 'delete_last_answers', :on => :member
        resources :questions do
          resources :tips
          resources :test_cases
          collection {post :sort}
        end
        collection { post :sort }
      end
    end
  end

  #get "answers_panel/index"
  #get "answers_panel/answers"

  namespace :newapi do
    resources :users, :only => [:index]
    resources :answers, :only => [:show] do
      member do
        get "connections"
        get "connected_component"
        get "similar"
      end
      collection do
        post "connections", action: :group_connections
        post "group"
      end
    end
    resources :connections, :only => [:create] do
      member do
        delete "reject_connection"
        put "accept_connection"
      end
    end
  end

  namespace :panel do
    #get "retroaction/:answer_id", :action => :retroaction
    #get "index"
    #get "comments"
    #get "explorer"
    resources :teams, only: [:show] do
      resources :los, only: [] do
        get 'overview', on: :member
      end
      resources :users, only: [:show] do
        resources :los, only: [:show] do
          resources :questions, only: [:show] do
            resources :answers, only: [:show] do
              post 'change_correctness', on: :member
              get 'try_again', on: :member
            end
          end
        end
      end
    end
  end

  #namespace :explorer do
  #  get "index"
  #  get "load_users"
  #  post "info_answer"
  #  post "info_connection"
  #  put "search"
  #  put "fulltext_search"
  #end

  namespace :dashboard do
    get "home"

    get "help"
    get "hide_help"

    post "graph_answer_info"
    post "graph_connection_info"

    get "search"
    get "timeline"
    get "graph"
    get "tags"

    put "fulltext_search/page/:page", action: "fulltext_search", as: "fulltext_search"
    put "timeline_search/page/:page", action: "timeline_search", as: "timeline_search"
    put "graph_search/page/:page", action: "graph_search", as: "graph_search"
    put "tags_search/page/:page", action: "tags_search", as: "tags_search"
    put "tags_search_aat", action: "tags_search_aat", as: "tags_search_aat"

    resources :teams, :only => [:new,:edit,:update,:create,:destroy] do
      post :unenroll, on: :member
    end
    namespace :teams do
      get "available"
      post "enroll"
    end

    namespace :answers do
      get "show"
    end

    namespace :connections do
      get "show"
    end

    resources :messages do
      resources :replies, :only => [:create,:destroy]
    end

    namespace :tags do
      get "show"
      put "add_tag"
      post "create_tag"
      delete "remove_tag"
      put "accept_tag"
      put "reject_tag"
    end
  end

  root to: "welcome#index"

  match '*path', to: 'home#index'
end

app/controllers/dashboard/answers_controller.rb
class Dashboard::AnswersController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!
  before_filter :can_view

  def can_view
    can = false
    @answer = Answer.find(params[:id])
    @answer.class_eval do
      attr_accessor :filter_names
    end

    @answer.filter_names = false

    if current_user.admin?
      can = true
    end

    if params.has_key?(:message_id)
      m = Message.find(params[:message_id])

      if m.target_user_ids.include?(current_user.id) and m.answer_ids.include?(params[:id])
        can = true

        @answer.filter_names = true
      end
    end

    if @answer.user_id == current_user.id
      can = true
    end

    if current_user.prof?
      if current_user.id.to_s == @answer.team.owner_id.to_s
        can = true
      end
    end


    unless can
      render :file => "public/401.html", :status => :unauthorized
    end
  end

  def show
    @available_tags = @answer.available_tags
    @answer.class_eval do
      attr_accessor :from_graph
    end

    if params.has_key?(:graph)
      @answer.from_graph = true
    else
      @answer.from_graph = false
    end

    Log.log_answer_view_simple(current_user.id,@answer.id)
  end

end

app/controllers/dashboard/connections_controller.rb
class Dashboard::ConnectionsController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!
  before_filter :can_view


  def can_view
    @connection = Connection.find(params[:id])
    @answer1 = Answer.find(@connection.answer_id)
    @answer2 = Answer.find(@connection.target_answer_id)

    can = false

    if current_user.admin?
      can = true
    end

    if @answer1.user_id == current_user.id && @answer2.user_id == current_user.id
      can = true
    end

    if current_user.prof?
      if @answer1.team.owner_id.to_s == current_user.id.to_s && @answer2.team.owner_id.to_s == current_user.id.to_s
        can = true
      end
    end

    unless can
      render_401
    end
  end

  def show
    Log.log_connection_view_simple(current_user.id,@connection.id)
  end
end

app/controllers/dashboard/messages_controller.rb
class Dashboard::MessagesController < ApplicationController
  layout "dashboard"

  before_filter :authenticate_user!
  before_filter :verify_prof, :except => [:index,:show]

  def get_available_users
    @available_users = []
    @users.each do |u|
      a = Hash.new
      a[:label] = u.name
      a[:value] = [u.id.to_s,"user_id"]
      @available_users << a
    end

    @teams.each do |t|
      a = Hash.new
      a[:label] = "Turma: " + t.name
      a[:value] = [t.id.to_s,"team_id"]
      @available_users << a
    end
  end

  def init_search
    @teams = current_user.all_teams
    @questions = current_user.all_questions
    @los = current_user.all_los
    @users = current_user.all_students
    @tags = current_user.all_tags
  end

  def index
    @messages = User.find(current_user.id).messages.desc(:created_at)

	@messages_to_me = Message.any_of({:target_user_ids => current_user.id}, {:user_ids => current_user.id.to_s}).desc(:created_at)

#    @messages_to_me = Message.where(:target_user_ids => current_user.id).desc(:updated_at)
  end

  def show
    @message = Message.find(params[:id])
    Log.log_message_view(current_user.id,@message.id)
    @message.new_flag_user_ids.delete(current_user.id)
    if current_user.id == @message.user.id
      @message.new_flag_user_id = false
    end
    @message.save!
    @reply = Reply.new
    get_messages
  end

  def new
    init_search
    get_available_users
    @method = :post
    @path = "/dashboard/messages"
    @message = Message.new(params[:message])

    if params.has_key?(:recom)
      Log.log_recommendation_click(current_user.id,params[:message])
    end
  end

  def edit
    init_search
    get_available_users
    @message = Message.find(params[:id])
    @path = "/dashboard/messages/"+params[:id]
    @method = :put
    render "new"
  end

  def create

    @message = Message.new(params[:message])

    @message.user_id = current_user.id
    @message.target_user_ids = []

    unless params[:message].nil?
      if params[:message].has_key?(:user_ids)
        @message.target_user_ids = params[:message][:user_ids]
      end
      if params[:message].has_key?(:team_ids)
        params[:message][:team_ids].each do |team_id|
          team = Team.find(team_id)
          @message.target_user_ids = @message.target_user_ids + team.user_ids
        end
      end
    end

    @message.new_flag_user_ids = @message.target_user_ids

    respond_to do |format|
      if @message.save
        if @message.has_recommendation?
          Log.log_message_sent_with_recommendation(current_user.id,@message.id)
        else
          Log.log_message_sent(current_user.id,@message.id)
        end

        format.html { redirect_to dashboard_messages_path, notice: 'Mensagem criada com sucesso.' }
        format.json { render json: @message, status: :created, location: @message }
      else
        init_search
        get_available_users
        format.html { render action: "new" }
        format.json { render json: @messages.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @message = Message.find(params[:id])

    @message.user_id = current_user.id

    unless params[:message].nil?
      if params[:message].has_key?(:user_ids)
        @message.target_user_ids = params[:message][:user_ids]
      end
      if params[:message].has_key?(:team_ids)
        params[:message][:team_ids].each do |team_id|
          team = Team.find(team_id)
          @message.target_user_ids = @message.target_user_ids + team.user_ids
        end
      end
    end

    @message.new_flag_user_ids = @message.target_user_ids

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to dashboard_message_path(@message), notice: 'Mensagem atualizada!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to "/dashboard/messages" }
      format.json { head :no_content }
    end
  end

end

app/controllers/dashboard/replies_controller.rb
class Dashboard::RepliesController < ApplicationController
  layout "dashboard"

  before_filter :authenticate_user!
  before_filter :get_message
  before_filter :can_post, :only => [:create]
  before_filter :can_delete, :only => [:delete]

  def get_message
    @message = Message.find(params[:message_id])
  end

  def can_post
    if (not @message.user_id == current_user.id) and (not @message.target_user_ids.include?(current_user.id.to_s))
      render_401
    end
  end

  def can_delete
    unless @message.user_id == current_user.id
      render_401
    end
  end

  def create

    @reply = Reply.new(params[:reply])

    @reply.user_id = current_user.id
    @reply.message_id = @message.id

    respond_to do |format|
      if @reply.save
        if @message.target_user_ids.nil? or @message.target_user_ids.empty?
          @message.new_flag_user_ids = @message.user_ids
        else
          @message.new_flag_user_ids = @message.target_user_ids
        end
        @message.save!
        format.html { redirect_to dashboard_message_path(@message), notice: 'Mensagem criada com sucesso.' }
        format.json { render json: @reply, status: :created, location: @message }
      else
        format.html { render "dashboard/messages/show" }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy

    respond_to do |format|
      format.html { redirect_to dashboard_message_path(@message) }
      format.json { head :no_content }
    end
  end

end

app/controllers/dashboard/tags_controller.rb
class Dashboard::TagsController < ApplicationController
  respond_to :json

  before_filter :authenticate_user!
  before_filter :verify_prof

  def verify_answer(a)
    if params.has_key?(:answer_id)
      unless current_user.all_team_ids.include?(Answer.find(params[:answer_id]).team_id)
        render_401
      end
    end
  end

  # ================================================================
  # ================================================================
  # TAGS MANIPULATION
  def show
    @answer = Answer.find(params[:answer_id])
    @available_tags = @answer.available_tags
  end

  def add_tag
    tag = Tag.where(:name => params[:query])
    @answer = Answer.find(params[:answer_id])

    if tag.count > 0
      @answer.tag_ids << tag.first.id.to_s
      @answer.rejected_tags.delete(tag.first.id.to_s)
      @answer.save!

      @answer.schedule_process_propagate
      Log.log_add_tag(current_user.id,@answer.id,tag.first.id)

      @available_tags = @answer.available_tags
      render :show
    else
      @tag = Tag.new
      @tag.name = params[:query]
      render :new
    end
  end

  def create_tag
    @tag = Tag.new(params[:tag])

    if @tag.save
      @answer = Answer.find(params[:answer_id])
      @answer.tag_ids << @tag.id.to_s
      @answer.save!

      @answer.schedule_process_propagate

      @available_tags = @answer.available_tags
      @notice = "Tag #{@tag.name} criada com sucesso!"

      Log.log_add_tag(current_user.id,@answer.id,@tag.id)
    end

    render :show
  end

  def remove_tag
    @answer = Answer.find(params[:answer_id])
    @answer.tag_ids.delete(params[:id])
    @answer.rejected_tags << params[:id]
    @answer.save!

    @answer.schedule_process_propagate
    @available_tags = @answer.available_tags

    Log.log_remove_tag(current_user.id,@answer.id,params[:id])

    render :show
  end

  def accept_tag
    @answer = Answer.find(params[:answer_id])
    @tag = Tag.find(params[:id])

    @answer.tag_ids << @tag.id.to_s

    i = @answer.automatically_assigned_tags.index{ |x| x[0].to_s == @tag.id.to_s }
    @answer.automatically_assigned_tags.delete_at(i)
    @answer.save!
    @available_tags = @answer.available_tags

    Log.log_accept_tag(current_user.id,@answer.id,@tag.id)

    if params.has_key?(:not_render)
      render :nothing => true
    else
      render :show
    end
  end

  def reject_tag
    @answer = Answer.find(params[:answer_id])

    @tag = Tag.find(params[:id])

    i = @answer.automatically_assigned_tags.index{ |x| x[0].to_s == @tag.id.to_s }
    @answer.automatically_assigned_tags.delete_at(i)
    @answer.rejected_tags << @tag.id.to_s
    @answer.save!
    @answer.schedule_process_propagate
    @available_tags = @answer.available_tags

    Log.log_reject_tag(current_user.id,@answer.id,@tag.id)

    if params.has_key?(:not_render)
      render :nothing => true
    else
      render :show
    end
  end
  # ================================================================
  # ================================================================

end

app/controllers/dashboard/teams_controller.rb
class Dashboard::TeamsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :verify_prof, :only =>[:new, :update, :edit, :create,:destroy]
  before_filter :can_edit?, :only =>[:update, :edit, :destroy]

  layout "dashboard"

  def can_edit?
    unless current_user.id.to_s == Team.find(params[:id]).owner_id.to_s || current_user.admin?
      render_401
    end
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params[:team])
    @team.owner_id = current_user.id
    respond_to do |format|
      if @team.save
        format.html { redirect_to dashboard_teams_available_path, notice: 'Turma criada com sucesso.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to panel_team_path(@team.id), notice: 'Turma atualizada com sucesso.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def enroll
    t = Team.find(params[:team][:id])
    unless t.users.include?(current_user)
      if t.code == params[:password]
        t.users << current_user

        t.save!
      else
        @wrong_code_team_id = t.id
      end
    end
    #@teams = Team.all
    @teams = Team.where(active: true)

    render "available"
  end

  def unenroll
    @team = Team.find(params[:id])

    if @team.users.include?(current_user)
      @team.user_ids = @team.user_ids - [current_user.id]
      @team.save!
    end

    redirect_to dashboard_teams_available_path
  end

  def destroy
    @team = Team.find(params[:id])

    if @team.owner_id == current_user.id
      @team.destroy
    end

    redirect_to dashboard_teams_available_path
  end

  def available
    @teams = Team.where(active: true)
    @teams_unavailable = Team.where(active: false)
  end

end

app/views/dashboard/tags/_new.html.erb
<div class="well" style="padding:5px;">
<h4>Nova Tag</h4>

<%= form_for @tag, :url => dashboard_tags_create_tag_path, :remote => true, :html => {:method => :post, :id => "new_tag_form"} do |f| %>
	<%= f.label "name", "Nome" %>
  <%= f.text_field "name", :class => "form-control input" %>
  <%= f.label "description", "Descrição" %>
  <%= f.text_field "description", :class => "form-control input" %>
  <%= hidden_field_tag 'answer_id', @answer.id %>
  <%= f.label "type", "Tipo" %>
  <p>
  	<%= radio_button("tag", "type", "1") %> <span style="margin-right:5px;" class="label label-danger">1</span>
  	<%= radio_button("tag", "type", "2") %> <span style="margin-right:5px;" class="label label-warning">2</span>
  	<%= radio_button("tag", "type", "3",{checked: true}) %> <span style="margin-right:5px;" class="label label-success">3</span>
  </p>
  <%= f.submit "Enviar", :class => "btn btn-primary" %>
  <%= f.button "Cancelar", :type => "button", :class => "btn", :id => "new_tag_cancel" %>
<% end %>
</div>

app/views/dashboard/tags/_show.html.erb
<div id="overlay"></div>
      <h5>Confirmadas:</h5>
      <% answer.tags.each do |t| %>

        <% if t.type == 1 %>
          <% label = "label-danger" %>
        <% elsif t.type == 2 %>
          <% label = "label-warning" %>
        <% else %>
          <% label = "label-success" %>
        <% end %>

        <span style="margin: 3px 3px;" rel="tooltip" data-toggle="tooltip" data-placement="top" title data-original-title="<%= t.description %>" class="label <%= label %>"> <%= t.name %><a href="#" class="remove_tag_link" data-id="<%= t.id %>" data-answer-id="<%= @answer.id %>"><i class='fa fa-times' style="color:black;"></i></a> </span>
      <% end %>
      </div>

      <h5>Adicionadas automaticamente:</h5>
      <div id="aa_tags">
      <% answer.automatically_assigned_tags.each do |aat| %>

        <% t = Tag.find(aat[0]) %>

        <% if t.type == 1 %>
          <% label = "label-danger" %>
        <% elsif t.type == 2 %>
          <% label = "label-warning" %>
        <% else %>
          <% label = "label-success" %>
        <% end %>

        <span rel="tooltip" data-toggle="tooltip" data-placement="top" title data-original-title="<%= t.description %>" class="label <%= label %>"><%= t.name %> <span class="badge badge-default"><%= '%.2f' % aat[1] %></span> <a href="#" class="accept_tag_link" data-id="<%= t.id %>" data-answer-id="<%= @answer.id %>"> <i class='fa fa-check' style="color:black;"></i> </a>  <a href="#" class="reject_tag_link" data-id="<%= t.id %>" data-answer-id="<%= @answer.id %>"> <i class='fa fa-times' style="color:black;"></i></a> </span>&nbsp;
      <% end %>
      </div>

      <h5>Inserir tag</h5>
      <div>
        <%= form_tag dashboard_tags_add_tag_path, :remote => true, :method => :put, :id => "add_tag_form" do %>
          <%= text_field_tag "query", nil, :class => "form-control input", :id => "add_tag_field" %>
          <%= hidden_field_tag 'answer_id', @answer.id %>
        <% end %>
      </div>

      <div id="new_tag"></div>

      <div>

app/views/dashboard/tags/new.js.erb
$("#new_tag").html("<%= escape_javascript(render(:partial => 'new', :locals => {:answer => @answer, :tag => @tag}))%>");
$("#new_tag").show();

$("#add_tag_form").hide();

$("#new_tag_cancel").click(function(){
  $("#add_tag_form").show();
  $("#new_tag").hide();
  $("#add_tag_field").focus();
});

$("#tag_description").focus();

app/views/dashboard/tags/show.js.erb
$("#tags").html("<%= escape_javascript(render(:partial => 'show', :locals => {:answer => @answer}))%>");

$("span.label").tooltip();

var availableTags = <%= raw @available_tags.to_json %>;

function tags_loading(){
  $("#tags").html("Carregando tags ...");
}

$(".remove_tag_link").click(function(){
  tags_loading();
  $.ajax({
    url: "/dashboard/tags/remove_tag",
    data: {
      id: $(this).data("id"),
      answer_id: $(this).data("answer-id")
    },
    type: "delete"    
  });
});

$(".accept_tag_link").click(function(){
  tags_loading();
  $.ajax({
    url: "/dashboard/tags/accept_tag",
    data: {
      id: $(this).data("id"),
      answer_id: $(this).data("answer-id")
    },
    type: "put"    
  });
});

$(".reject_tag_link").click(function(){
  tags_loading();
  $.ajax({
    url: "/dashboard/tags/reject_tag",
    data: {
      id: $(this).data("id"),
      answer_id: $(this).data("answer-id")
    },
    type: "put"    
  });
});

$( "#add_tag_field" ).autocomplete({
  source: availableTags
});